Add attachments from the junit-attachments plugin into Jira attachments
jenkinsci/JiraTestResultReporter-plugin pull request #144
Opened 2024-04-19 16:01 UTC by imonteroperez

### Highlights
- Before this PR the attachments added to the Jira tickets are always the stderr, stdout and error stacktrace and details
- After this PR, if the test result has additional attachments provided by third-party tools (like the junit-attachments publisher) these would be also added to the Jira ticket.

### Testing done
- Tested with Jira and Jenkins locally and working as expected

- Jenkins attachment

![Captura de pantalla de 2024-04-21 21-30-54](https://github.com/jenkinsci/JiraTestResultReporter-plugin/assets/595347/4a1a7c86-c751-4417-8b7e-5f7f1eefe1ca)

- Jira attachment (contains the one from the junit-attachment in addition to the current ones - stderr, stdout, etc.)

![Captura de pantalla de 2024-04-21 21-30-34](https://github.com/jenkinsci/JiraTestResultReporter-plugin/assets/595347/7145bf39-c99d-4f30-b08a-c96bbb1146f7)

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

2024-04-22 08:22 UTC, imonteroperez commented on src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher.java
> +	/** Attachments obtained from junit-attachments plugin if installed **/
```suggestion
	/** Attachments obtained from junit-attachments plugin indexed by className and test method name **/
```

2024-04-22 18:25 UTC, cathychan reviewed
IMO this should be an opt-in feature. If I have some builds that have massive test attachments, I may not want to include them in the Jira tickets.

2024-04-22 18:25 UTC, cathychan commented on src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraUtils.java
> +            JiraUtils.log(String.format("Unable to access to attachment storage for %s:%s", test.getName(), test.getRun().getId()));
```suggestion
            JiraUtils.log(String.format("Unable to access attachment storage for %s:%s", test.getName(), test.getRun().getId()));
```

2024-04-22 19:17 UTC, imonteroperez commented
> IMO this should be an opt-in feature. If I have some builds that have massive test attachments, I may not want to include them in the Jira tickets.

LGTM, will add a configuration option

2024-04-23 07:34 UTC, imonteroperez commented
> > IMO this should be an opt-in feature. If I have some builds that have massive test attachments, I may not want to include them in the Jira tickets.
> 
> LGTM, will add a configuration option

Added a configuration option via `EnvVar` on https://github.com/jenkinsci/JiraTestResultReporter-plugin/pull/144/commits/ce6f0c7c74142eccd9ed76e7e904f1a5044044a7. I discarded to include an option to the step to keep it simple and keep backward compatibility. Also, the step options are there to specify the behavior (raise, resolve, etc.) but here we want a specific additional operation on raising Jira issues, so that is the reason why I decided to go through an env var.

2024-04-23 07:39 UTC, imonteroperez commented on src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher.java
> +    public static final boolean DEBUG = false;
```suggestion
	public static final boolean DEBUG = false;
```

2024-04-23 11:12 UTC, jglick requested changes

2024-04-23 11:12 UTC, jglick commented on README.md
> + * `JIRA_INCLUDE_JUNIT_ATTACHMENTS`: it will include as attachments of a Jira issue additional files from [junit-attachments](https://github.com/jenkinsci/junit-attachments-plugin) plugin. Only on ra
Why an environment variable and not just a regular `boolean` data bound setter on the publisher?

2024-04-23 11:12 UTC, jglick commented on src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher.java
> +                GetTestDataMethodObject methodObject = new GetTestDataMethodObject(run, workspace, launcher, listener, testResult);
TIL: https://github.com/jenkinsci/junit-attachments-plugin/blob/7ca5b7a98b1c215fcd2aa21a1510c03f1b488466/src/main/java/hudson/plugins/junitattachments/GetTestDataMethodObject.java#L31-L32 does not seem to accurately describe what that class does at all.

2024-04-23 11:12 UTC, jglick commented on src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher.java
>  	EnvVars envVars = run.getEnvironment(listener);
This gets the top-level environment for the build. `withEnv` does not affect it.

2024-04-23 11:15 UTC, imonteroperez commented on src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher.java
>  	EnvVars envVars = run.getEnvironment(listener);
You are right, actually, I'm testing this right now and detected this issue. TBH rethinking on to setup a boolean data bound setter better than this.

2024-04-23 11:18 UTC, imonteroperez commented on README.md
> + * `JIRA_INCLUDE_JUNIT_ATTACHMENTS`: it will include as attachments of a Jira issue additional files from [junit-attachments](https://github.com/jenkinsci/junit-attachments-plugin) plugin. Only on ra
At the very beginning considered this https://github.com/jenkinsci/JiraTestResultReporter-plugin/pull/144#issuecomment-2071625826 but I'm reconsidering this option and return to the boolean data bound setter on the publisher

2024-04-23 11:19 UTC, imonteroperez commented on src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher.java
> +                GetTestDataMethodObject methodObject = new GetTestDataMethodObject(run, workspace, launcher, listener, testResult);
It retrieves all the attachments per test class and method

2024-04-23 11:24 UTC, jglick commented on README.md
> + * `JIRA_INCLUDE_JUNIT_ATTACHMENTS`: it will include as attachments of a Jira issue additional files from [junit-attachments](https://github.com/jenkinsci/junit-attachments-plugin) plugin. Only on ra
All configuration of Pipeline steps, or structs used inside steps (this case), should be via regular data binding. It should be self-documenting as well, using `config.jelly`. See [docs](https://www.jenkins.io/doc/developer/plugin-development/pipeline-integration/).

2024-04-23 11:42 UTC, imonteroperez commented on src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher.java
>  	EnvVars envVars = run.getEnvironment(listener);
Addressed in https://github.com/jenkinsci/JiraTestResultReporter-plugin/pull/144/commits/a384e3c2c877576763c7137ef14488508927a1d9

2024-04-23 11:42 UTC, imonteroperez commented on README.md
> + * `JIRA_INCLUDE_JUNIT_ATTACHMENTS`: it will include as attachments of a Jira issue additional files from [junit-attachments](https://github.com/jenkinsci/junit-attachments-plugin) plugin. Only on ra
Done in https://github.com/jenkinsci/JiraTestResultReporter-plugin/pull/144/commits/a384e3c2c877576763c7137ef14488508927a1d9

2024-04-23 19:13 UTC, jglick commented on src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher.java
> +                                 boolean additionalAttachments) {
Better to use `@DataBoundSetter`. https://www.jenkins.io/doc/developer/plugin-development/pipeline-integration/#constructor-vs-setters

2024-04-24 08:10 UTC, imonteroperez commented on src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher.java
> +                                 boolean additionalAttachments) {
I will do this refactoring outside the scope of this PR. Not sure which parameters can be delegated to a setter given documentation said this is for optional ones.

2024-04-24 20:35 UTC, jglick commented on src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher.java
> +                                 boolean additionalAttachments) {
Well the _new_ option you just added is clearly optional and so it should be added via a `@DataBoundSetter`. Refactoring _existing_ options is another matter, but you should never be adding parameters to an existing `@DataBoundConstructor`.

2024-04-25 07:55 UTC, imonteroperez commented on src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher.java
> +                                 boolean additionalAttachments) {
Addresed for the new optional field in https://github.com/jenkinsci/JiraTestResultReporter-plugin/pull/144/commits/d96ed87ceeefc981a585342cae000b53a2b0800d

2024-04-25 13:14 UTC, imonteroperez commented on src/main/java/org/jenkinsci/plugins/JiraTestResultReporter/JiraTestDataPublisher.java
> +    public void setAdditionalAttachments(boolean additionalAttachments) {
Addressed on https://github.com/jenkinsci/JiraTestResultReporter-plugin/pull/144/commits/86b36798e27cbd6653295a21c0c02cae5b76d25f

2024-04-25 14:27 UTC, jglick approved these changes
Looks OK.

2024-04-26 07:17 UTC, merged